# Generated by Django 5.2.1 on 2026-09-17 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('categories', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_found', models.PositiveIntegerField(default=0)),
                ('no_website_count', models.PositiveIntegerField(default=0)),
                ('priority_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leads_search_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='leads_searc_status_e8ff3e_idx'), models.Index(fields=['city', 'country'], name='leads_searc_city_ce3fd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('html', 'HTML Report')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='leads.searchjob')),
            ],
            options={
                'db_table': 'leads_export_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, default='')),
                ('has_website', models.BooleanField(default=False)),
                ('whatsapp_status', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp_check_link', models.URLField(blank=True, default='')),
                ('osm_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.searchjob')),
            ],
            options={
                'db_table': 'leads_lead',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search_job', 'has_website'], name='leads_lead_search__33215a_idx'), models.Index(fields=['search_job', 'whatsapp_status'], name='leads_lead_search__baa22f_idx')],
            },
        ),
    ]
